// BCL Review Rewards — AWS Amplify backend (Cognito + DynamoDB via AppSync + S3)
//
// This file loads at the bottom of index.html. It:
//   1. Fetches amplify_outputs.json (generated by `ampx pipeline-deploy`)
//   2. Configures Amplify
//   3. Renders the right screen depending on auth state
//   4. Handles all CRUD against the Amplify Data client + S3 Storage
//
// Everything is async/await. No localStorage state lives here — the only
// localStorage we touch is Amplify's internal token cache (managed by the SDK).

import { Amplify } from 'aws-amplify';
import {
  signIn, signOut, confirmSignIn, fetchAuthSession, getCurrentUser,
  resetPassword, confirmResetPassword, fetchUserAttributes
} from 'aws-amplify/auth';
import { generateClient } from 'aws-amplify/data';
import { uploadData, getUrl, remove as removeFromStorage } from 'aws-amplify/storage';

// ----------------------------- TIERS / EARNINGS ---------------------------
const TIERS = [
  { n: 1, amt: 1000, label: '1st review', sub: 'First one this month' },
  { n: 2, amt: 1250, label: '2nd review', sub: 'Building momentum' },
  { n: 3, amt: 1500, label: '3rd review', sub: 'Halfway there' },
  { n: 4, amt: 1750, label: '4th review', sub: 'Almost there' },
  { n: 5, amt: 2000, label: '5th review', sub: 'Full tier complete!' },
];
const TERMS = [
  'Rewards reset at the start of each calendar month — the 1st review always starts at ₹1,000 regardless of previous months.',
  'Reviews must be from your own clients only — reviews from another team member\'s client will not be counted.',
  'Maximum of 10 qualifying reviews per person per month. Reviews beyond the cap will not attract additional reward.',
  'Reviews must be posted on Google or Trustpilot to qualify.',
  'Rewards are paid out at the end of each month upon verification.',
  'Management reserves the right to amend or withdraw the program at any time with reasonable notice.'
];
function calcEarnings(count) {
  let t = 0;
  for (let i = 1; i <= Math.min(count, 10); i++) t += i <= 5 ? TIERS[i - 1].amt : 2000;
  return t;
}
function nextAmt(count, cap = 10) {
  if (count >= cap) return null;
  return count < 5 ? TIERS[count].amt : 2000;
}
function fmtINR(n) { return '₹' + Number(n).toLocaleString('en-IN'); }
function currentMonthKey() {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`;
}

// ----------------------------- MONTH NAVIGATION ----------------------------
const PROGRAM_START = { year: 2025, month: 4 };
function buildMonthList() {
  const now = new Date(), months = [];
  let y = PROGRAM_START.year, m = PROGRAM_START.month;
  const endY = now.getFullYear(), endM = now.getMonth() + 1;
  while (y * 12 + m <= endY * 12 + endM) {
    const d = new Date(y, m - 1, 1);
    months.push({
      key: `${y}-${String(m).padStart(2, '0')}`,
      label: d.toLocaleDateString('en-IN', { month: 'long', year: 'numeric' })
    });
    m++; if (m > 12) { m = 1; y++; }
  }
  return months;
}
const MONTH_LIST = buildMonthList();
const TODAY_KEY = currentMonthKey();
let selectedMonth = TODAY_KEY;

function monthPickerHTML(id) {
  const opts = MONTH_LIST.slice().reverse().map(m =>
    `<option value="${m.key}" ${m.key === selectedMonth ? 'selected' : ''} style="background:#26215C;color:white;">${m.label}${m.key === TODAY_KEY ? ' ✦' : ''}</option>`
  ).join('');
  return `<select id="${id}" class="month-picker">${opts}</select>`;
}

function setMonth(key) {
  selectedMonth = key;
  const lockEl = document.getElementById('submit-lock-notice');
  if (lockEl) {
    const isCurrent = (key === TODAY_KEY);
    lockEl.classList.toggle('hidden', isCurrent);
    const lblEl = document.getElementById('lock-month-label');
    if (lblEl) {
      const monthLabel = MONTH_LIST.find(m => m.key === key)?.label || key;
      lblEl.textContent = monthLabel;
    }
  }
  if (currentRole === 'staff') refreshStaff();
}

// ----------------------------- BOOT ----------------------------------------
const bootSpinner = document.getElementById('boot-spinner');
const bootMsg = document.getElementById('boot-msg');
function bootMessage(t) { bootMsg.textContent = t; }
function hideBoot() { bootSpinner.classList.add('hidden'); }
function showBoot(t) { bootSpinner.classList.remove('hidden'); bootMessage(t); }

let client; // Amplify Data client
let currentRole = null;
let currentEmail = null;
let currentName = null;

(async function boot() {
  try {
    bootMessage('Loading config…');
    const r = await fetch('amplify_outputs.json', { cache: 'no-store' });
    if (!r.ok) throw new Error('amplify_outputs.json not found — the backend has not been deployed yet.');
    const outputs = await r.json();
    Amplify.configure(outputs);
    client = generateClient({ authMode: 'userPool' });

    bootMessage('Checking session…');
    try {
      const user = await getCurrentUser();
      currentEmail = user.signInDetails?.loginId || user.username;
      await loadProfileAndRoute();
    } catch {
      hideBoot();
      showLogin();
    }
  } catch (e) {
    hideBoot();
    showLogin();
    showLoginError('Cannot reach backend: ' + (e.message || e));
  }
})();

async function loadProfileAndRoute() {
  // Fetch tokens to learn group membership; fetch attributes for the display name
  const session = await fetchAuthSession();
  const groups = session.tokens?.idToken?.payload?.['cognito:groups'] || [];
  currentRole = groups.includes('admin') ? 'admin' : groups.includes('staff') ? 'staff' : null;

  try {
    const attrs = await fetchUserAttributes();
    currentName = attrs.name || attrs.email || currentEmail;
    currentEmail = (attrs.email || currentEmail).toLowerCase();
  } catch { /* ignore */ }

  hideBoot();

  if (!currentRole) {
    showLogin();
    showLoginError('Your account exists but no admin has assigned a role yet. Ask your admin to add you to the "staff" or "admin" group.');
    await signOut().catch(() => {});
    return;
  }

  if (currentRole === 'admin') showAdmin();
  else showStaff();
}

// ----------------------------- SCREEN SWITCHING ----------------------------
function hideAllScreens() {
  ['login-wrap','newpw-wrap','forgot-wrap','staff-wrap','admin-wrap']
    .forEach(id => document.getElementById(id).classList.add('hidden'));
}
function showLogin() {
  hideAllScreens();
  document.getElementById('login-wrap').classList.remove('hidden');
  document.getElementById('login-error').classList.add('hidden');
}
function showLoginError(msg) {
  const el = document.getElementById('login-error');
  el.textContent = msg;
  el.classList.remove('hidden');
}

// ----------------------------- AUTH HANDLERS -------------------------------
let pendingChallengeUser = null;

document.getElementById('login-btn').addEventListener('click', async () => {
  const email = document.getElementById('login-email').value.trim().toLowerCase();
  const pwd = document.getElementById('login-pwd').value;
  const errEl = document.getElementById('login-error');
  errEl.classList.add('hidden');
  if (!email || !pwd) { showLoginError('Enter both email and password.'); return; }
  const btn = document.getElementById('login-btn');
  btn.disabled = true; btn.innerHTML = '<span class="spinner"></span>Signing in…';
  try {
    const { isSignedIn, nextStep } = await signIn({ username: email, password: pwd });
    if (isSignedIn) {
      currentEmail = email;
      showBoot('Loading your account…');
      await loadProfileAndRoute();
      return;
    }
    if (nextStep.signInStep === 'CONFIRM_SIGN_IN_WITH_NEW_PASSWORD_REQUIRED') {
      pendingChallengeUser = email;
      hideAllScreens();
      document.getElementById('newpw-wrap').classList.remove('hidden');
      return;
    }
    showLoginError('Unexpected next step: ' + nextStep.signInStep);
  } catch (e) {
    showLoginError(humanAuthError(e));
  } finally {
    btn.disabled = false; btn.innerHTML = 'Sign in →';
  }
});

document.getElementById('newpw-btn').addEventListener('click', async () => {
  const pwd = document.getElementById('newpw-pwd').value;
  const pwd2 = document.getElementById('newpw-pwd2').value;
  const errEl = document.getElementById('newpw-error');
  errEl.classList.add('hidden');
  if (pwd.length < 8) { errEl.textContent = 'Password must be at least 8 characters.'; errEl.classList.remove('hidden'); return; }
  if (pwd !== pwd2) { errEl.textContent = 'Passwords do not match.'; errEl.classList.remove('hidden'); return; }
  const btn = document.getElementById('newpw-btn');
  btn.disabled = true; btn.innerHTML = '<span class="spinner"></span>Saving…';
  try {
    const res = await confirmSignIn({ challengeResponse: pwd });
    if (res.isSignedIn) {
      currentEmail = pendingChallengeUser;
      showBoot('Loading your account…');
      await loadProfileAndRoute();
    } else {
      errEl.textContent = 'Unexpected step: ' + res.nextStep?.signInStep;
      errEl.classList.remove('hidden');
    }
  } catch (e) {
    errEl.textContent = humanAuthError(e);
    errEl.classList.remove('hidden');
  } finally {
    btn.disabled = false; btn.innerHTML = 'Save & continue →';
  }
});

document.getElementById('forgot-link').addEventListener('click', (e) => {
  e.preventDefault();
  hideAllScreens();
  document.getElementById('forgot-wrap').classList.remove('hidden');
  document.getElementById('forgot-step1').classList.remove('hidden');
  document.getElementById('forgot-step2').classList.add('hidden');
  document.getElementById('forgot-email').value = document.getElementById('login-email').value;
});

document.getElementById('forgot-back').addEventListener('click', (e) => {
  e.preventDefault(); showLogin();
});

document.getElementById('forgot-btn').addEventListener('click', async () => {
  const email = document.getElementById('forgot-email').value.trim().toLowerCase();
  const errEl = document.getElementById('forgot-error');
  errEl.classList.add('hidden');
  if (!email) { errEl.textContent = 'Enter your email.'; errEl.classList.remove('hidden'); return; }
  const btn = document.getElementById('forgot-btn');
  btn.disabled = true; btn.innerHTML = '<span class="spinner"></span>Sending…';
  try {
    await resetPassword({ username: email });
    document.getElementById('forgot-step1').classList.add('hidden');
    document.getElementById('forgot-step2').classList.remove('hidden');
    document.getElementById('forgot-sub').textContent = 'A 6-digit code was emailed to you. It may take a minute.';
  } catch (e) {
    errEl.textContent = humanAuthError(e);
    errEl.classList.remove('hidden');
  } finally {
    btn.disabled = false; btn.innerHTML = 'Send reset code →';
  }
});

document.getElementById('forgot-confirm-btn').addEventListener('click', async () => {
  const email = document.getElementById('forgot-email').value.trim().toLowerCase();
  const code = document.getElementById('forgot-code').value.trim();
  const newPw = document.getElementById('forgot-newpw').value;
  const errEl = document.getElementById('forgot-error2');
  errEl.classList.add('hidden');
  if (!code || newPw.length < 8) { errEl.textContent = 'Enter the code and a password of 8+ characters.'; errEl.classList.remove('hidden'); return; }
  const btn = document.getElementById('forgot-confirm-btn');
  btn.disabled = true; btn.innerHTML = '<span class="spinner"></span>Saving…';
  try {
    await confirmResetPassword({ username: email, confirmationCode: code, newPassword: newPw });
    showLogin();
    document.getElementById('login-email').value = email;
    toast('Password updated. Sign in with your new password.', 'success');
  } catch (e) {
    errEl.textContent = humanAuthError(e);
    errEl.classList.remove('hidden');
  } finally {
    btn.disabled = false; btn.innerHTML = 'Save new password →';
  }
});

// ----------------------------- STAFF SCREEN --------------------------------
let staffReviews = [];
function showStaff() {
  hideAllScreens();
  document.getElementById('staff-wrap').classList.remove('hidden');
  document.getElementById('staff-greeting').textContent = `Hi ${currentName?.split(' ')[0] || 'there'} 👋`;
  selectedMonth = TODAY_KEY;
  const mpHost = document.getElementById('staff-month-picker-host');
  if (mpHost) {
    mpHost.innerHTML = monthPickerHTML('staff-month-sel');
    const sel = document.getElementById('staff-month-sel');
    if (sel) sel.addEventListener('change', e => setMonth(e.target.value));
  }
  const lockEl = document.getElementById('submit-lock-notice');
  if (lockEl) lockEl.classList.add('hidden');
  loadAnnouncement();
  switchStaffTab('submit');
  refreshStaff();
}

document.querySelectorAll('#staff-wrap .tab').forEach(t => {
  t.addEventListener('click', () => switchStaffTab(t.dataset.tab));
});
function switchStaffTab(name) {
  document.querySelectorAll('#staff-wrap .tab').forEach(t => t.classList.toggle('active', t.dataset.tab === name));
  document.getElementById('staff-tab-submit').classList.toggle('hidden', name !== 'submit');
  document.getElementById('staff-tab-history').classList.toggle('hidden', name !== 'history');
  document.getElementById('staff-tab-tiers').classList.toggle('hidden', name !== 'tiers');
  if (name === 'history' || name === 'submit' || name === 'tiers') refreshStaff();
}

document.getElementById('staff-signout').addEventListener('click', doSignOut);
document.getElementById('admin-signout').addEventListener('click', doSignOut);
async function doSignOut() {
  try { await signOut(); } catch {}
  currentRole = currentEmail = currentName = null;
  showLogin();
}

// Upload handlers
const uploadZone = document.getElementById('staff-upload-zone');
const fileInput = document.getElementById('staff-file');
let pendingFile = null;
uploadZone.addEventListener('click', () => fileInput.click());
uploadZone.addEventListener('dragover', e => { e.preventDefault(); uploadZone.classList.add('dragover'); });
uploadZone.addEventListener('dragleave', () => uploadZone.classList.remove('dragover'));
uploadZone.addEventListener('drop', e => {
  e.preventDefault(); uploadZone.classList.remove('dragover');
  if (e.dataTransfer.files[0]) handleStaffFile(e.dataTransfer.files[0]);
});
fileInput.addEventListener('change', e => { if (e.target.files[0]) handleStaffFile(e.target.files[0]); });
function handleStaffFile(file) {
  if (selectedMonth !== TODAY_KEY) { toast('You can only submit reviews for the current month.', 'warning'); return; }
  if (file.size > 5 * 1024 * 1024) { toast('Image too large (max 5 MB).', 'warning'); return; }
  pendingFile = file;
  const url = URL.createObjectURL(file);
  const img = document.getElementById('staff-preview');
  img.src = url; img.classList.remove('hidden');
  document.getElementById('staff-upload-title').textContent = file.name;
  document.getElementById('staff-upload-icon').textContent = '✓';
  // Show verify result preview
  const month = TODAY_KEY;
  const thisMonth = staffReviews.filter(r => r.monthKey === month);
  const total = thisMonth.length;
  const verifyEl = document.getElementById('staff-verify-area');
  const resultEl = document.getElementById('staff-verify-result');
  if (total >= 10) {
    if (resultEl) resultEl.innerHTML = '<div class="alert alert-warning">You have reached your review cap (10) for this month.</div>';
    if (verifyEl) verifyEl.classList.remove('hidden');
    document.getElementById('staff-submit-area').classList.add('hidden');
  } else {
    const nextNum = total + 1;
    const reward = nextNum <= 5 ? TIERS[nextNum - 1].amt : 2000;
    if (resultEl) resultEl.innerHTML = `<div class="alert alert-success">✓ Screenshot ready! This will be Review #${nextNum} and earns <strong>${fmtINR(reward)}</strong> once approved by admin.</div>`;
    if (verifyEl) verifyEl.classList.remove('hidden');
    document.getElementById('staff-submit-area').classList.remove('hidden');
  }
}

document.getElementById('staff-submit-btn').addEventListener('click', async () => {
  if (!pendingFile) return;
  if (selectedMonth !== TODAY_KEY) { toast('You can only submit reviews for the current month.', 'warning'); return; }
  const monthKey = TODAY_KEY;
  const approvedCount = staffReviews.filter(r => r.status === 'approved').length;
  const totalThisMonth = staffReviews.filter(r => r.monthKey === monthKey).length;
  if (totalThisMonth >= 10) { toast('You\'ve reached the 10/month cap.', 'warning'); return; }

  const btn = document.getElementById('staff-submit-btn');
  btn.disabled = true; btn.innerHTML = '<span class="spinner"></span>Uploading…';
  const msgEl = document.getElementById('staff-msg');
  msgEl.innerHTML = '';

  try {
    // Build a stable key. {entity_id} placeholder is the user's identityId.
    const ext = (pendingFile.name.split('.').pop() || 'jpg').toLowerCase();
    const id = crypto.randomUUID();
    // Capture the actually-resolved path so admins can read it later
    let resolvedPath = '';
    await uploadData({
      path: ({ identityId }) => {
        resolvedPath = `reviews/${identityId}/${monthKey}/${id}.${ext}`;
        return resolvedPath;
      },
      data: pendingFile,
      options: { contentType: pendingFile.type || 'image/jpeg' },
    }).result;

    // Record the review in DynamoDB with the full path
    const stored = (await client.models.Review.create({
      userName: currentName || currentEmail,
      monthKey,
      platform: 'Google',
      status: 'pending',
      screenshotPath: resolvedPath,
      submittedAt: new Date().toISOString(),
    }));

    if (stored.errors?.length) throw new Error(stored.errors[0].message);

    msgEl.innerHTML = '<div class="alert alert-success">✓ Submitted. Admin will review shortly.</div>';
    pendingFile = null;
    fileInput.value = '';
    document.getElementById('staff-preview').classList.add('hidden');
    document.getElementById('staff-upload-title').textContent = 'Click here or drag a screenshot';
    document.getElementById('staff-upload-icon').textContent = '📸';
    document.getElementById('staff-submit-area').classList.add('hidden');
    document.getElementById('staff-verify-area').classList.add('hidden');
    refreshStaff();
  } catch (e) {
    msgEl.innerHTML = `<div class="alert alert-danger">Upload failed: ${e.message || e}</div>`;
  } finally {
    btn.disabled = false; btn.innerHTML = 'Submit for approval →';
  }
});

async function refreshStaff() {
  try {
    const res = await client.models.Review.list({
      // owner-scoped: implicit, only own rows are returned by Amplify auth
    });
    if (res.errors?.length) throw new Error(res.errors[0].message);
    staffReviews = res.data || [];
    const month = selectedMonth;
    const thisMonth = staffReviews.filter(r => r.monthKey === month);
    const approved = thisMonth.filter(r => r.status === 'approved').length;
    const pending = thisMonth.filter(r => r.status === 'pending').length;
    const total = approved + pending;
    document.getElementById('staff-count').textContent = total;
    document.getElementById('staff-earned').textContent = fmtINR(calcEarnings(approved));
    const nxt = nextAmt(approved);
    document.getElementById('staff-next').textContent = nxt ? fmtINR(nxt) : 'Max!';
    // Progress card + stats grid
    const pct = Math.min(100, Math.round((Math.min(approved, 5) / 5) * 100));
    const progFill = document.getElementById('prog-fill');
    const progPct = document.getElementById('prog-pct');
    const progLabel = document.getElementById('prog-label');
    const psCount = document.getElementById('ps-count');
    const psEarned = document.getElementById('ps-earned');
    if (progFill) progFill.style.width = pct + '%';
    if (progPct) progPct.textContent = pct + '%';
    if (progLabel) progLabel.textContent = Math.min(approved, 5) + ' of 5 tiers complete';
    if (psCount) psCount.textContent = total;
    if (psEarned) psEarned.textContent = fmtINR(calcEarnings(approved));
    renderTiers(approved);
    renderTerms();
    renderStaffHistory(thisMonth);
  } catch (e) {
    document.getElementById('staff-history-list').innerHTML =
      `<div class="alert alert-danger">Could not load reviews: ${e.message || e}</div>`;
  }
}

function renderTiers(approved) {
  const host = document.getElementById('tier-list');
  if (!host) return;
  let html = '';
  TIERS.forEach(t => {
    const earned = approved >= t.n;
    const isNext = approved === t.n - 1;
    html += `<div class="tier-row ${earned ? 'earned' : isNext ? 'next' : ''}">
      <div style="display:flex;align-items:center;">
        <span class="stars">${'★'.repeat(t.n)}</span>
        <div style="margin-left:9px;">
          <div class="tier-name">${t.label}</div>
          <div class="tier-sub">${t.sub}</div>
        </div>
      </div>
      <div class="tier-amt" style="color:${earned ? 'var(--green)' : isNext ? 'var(--purple)' : 'var(--text3)'};">${fmtINR(t.amt)}</div>
    </div>`;
  });
  html += `<div class="tier-row ${approved >= 6 ? 'earned' : ''}">
    <div style="display:flex;align-items:center;">
      <span class="stars">★★★★★<span style="font-size:10px;">+</span></span>
      <div style="margin-left:9px;">
        <div class="tier-name">6th-10th review</div>
        <div class="tier-sub">Every additional review</div>
      </div>
    </div>
    <div class="tier-amt" style="color:${approved >= 6 ? 'var(--green)' : 'var(--purple)'};">₹2,000 each</div>
  </div>`;
  host.innerHTML = html;
}

function renderTerms() {
  const host = document.getElementById('terms-list');
  if (!host) return;
  host.innerHTML = TERMS.map((t, i) =>
    `<div class="check-item"><div class="check-dot" style="${i === TERMS.length - 1 ? 'background:var(--text3);opacity:.5;' : ''}"></div><span style="${i === TERMS.length - 1 ? 'opacity:.6;' : ''}">${escapeHtml(t)}</span></div>`
  ).join('');
}
async function renderStaffHistory(reviews) {
  const host = document.getElementById('staff-history-list');
  if (!reviews.length) {
    host.innerHTML = '<div style="text-align:center;padding:2.5rem;color:var(--text3);font-size:13px;">No reviews this month yet.</div>';
    return;
  }
  // Sort newest first
  reviews = [...reviews].sort((a, b) => (b.submittedAt || '').localeCompare(a.submittedAt || ''));
  // Build rows in parallel, including signed URLs for thumbnails
  const rows = await Promise.all(reviews.map(async (r, idx) => {
    let thumbUrl = '';
    try {
      if (r.screenshotPath) {
        const u = await getUrl({ path: r.screenshotPath, options:{ expiresIn: 3600 } });
        thumbUrl = u.url.toString();
      }
    } catch {}
   const dateStr = r.submittedAt ? new Date(r.submittedAt).toLocaleDateString('en-GB', { day:'2-digit', month:'short' }) : '';
    const canWithdraw = r.status === 'pending' && r.monthKey === TODAY_KEY;
    return `<div class="history-row">
      <div class="history-thumb" data-url="${thumbUrl}" style="background-image:url('${thumbUrl}');"></div>
      <div style="flex:1;min-width:0;">
        <div style="font-size:13px;font-weight:500;">Review #${reviews.length - idx} · ${r.platform || 'Google'}</div>
        <div style="font-size:11px;color:var(--text3);">${dateStr}</div>
        ${r.status === 'rejected' && r.adminComment
          ? `<div style="font-size:12px;color:var(--red);margin-top:4px;padding:5px 9px;background:var(--red-light);border-radius:4px;">Admin: ${escapeHtml(r.adminComment)}</div>`
          : ''}
      </div>
      <div style="text-align:right;display:flex;flex-direction:column;align-items:flex-end;gap:5px;">
        <span class="badge badge-${r.status}">${r.status}</span>
        ${canWithdraw ? `<button class="btn btn-danger btn-sm" data-withdraw="${r.id}" style="font-size:11px;padding:4px 10px;">Withdraw</button>` : ''}
      </div>
    </div>`;
  }));
  host.innerHTML = rows.join('');
  host.querySelectorAll('[data-withdraw]').forEach(b => b.addEventListener('click', () => withdrawReview(b.dataset.withdraw)));
  host.querySelectorAll('.history-thumb').forEach(t => t.addEventListener('click', () => openLightbox(t.dataset.url)));
}

// ----------------------------- ADMIN SCREEN --------------------------------
function showAdmin() {
  hideAllScreens();
  document.getElementById('admin-wrap').classList.remove('hidden');
  switchAdminTab('pending');
  loadAdminAnnouncement();
}
document.querySelectorAll('#admin-wrap .tab').forEach(t => {
  t.addEventListener('click', () => switchAdminTab(t.dataset.atab));
});
function switchAdminTab(name) {
  document.querySelectorAll('#admin-wrap .tab').forEach(t => t.classList.toggle('active', t.dataset.atab === name));
  ['pending','approved','rejected','users'].forEach(n => {
    document.getElementById('admin-tab-' + n).classList.toggle('hidden', n !== name);
  });
  if (name === 'pending') loadAdminList('pending');
  if (name === 'approved') loadAdminList('approved');
  if (name === 'rejected') loadAdminList('rejected');
}

async function loadAdminList(status) {
  const host = document.getElementById('admin-' + status + '-list');
  host.innerHTML = '<div style="color:var(--text3);font-size:13px;text-align:center;padding:24px 0;"><span class="spinner"></span>Loading…</div>';
  try {
    const res = await client.models.Review.list({
      filter: { status: { eq: status } },
      limit: 200,
    });
    if (res.errors?.length) throw new Error(res.errors[0].message);
    const reviews = res.data || [];
    if (status === 'pending') {
      document.getElementById('admin-pending-count').textContent = reviews.length;
      document.getElementById('admin-pending-plural').textContent = reviews.length === 1 ? '' : 's';
      const badge = document.getElementById('admin-pending-badge');
      if (badge) {
        badge.textContent = reviews.length;
        badge.classList.toggle('hidden', reviews.length === 0);
      }
    }
    if (!reviews.length) {
      host.innerHTML = `<div style="text-align:center;padding:2.5rem;color:var(--text3);font-size:13px;">No ${status} reviews.</div>`;
      return;
    }
    reviews.sort((a, b) => (b.submittedAt || '').localeCompare(a.submittedAt || ''));
    const rows = await Promise.all(reviews.map(r => renderAdminRow(r, status)));
    host.innerHTML = rows.join('');
    // Wire approve/reject for pending
    host.querySelectorAll('[data-approve]').forEach(btn => btn.addEventListener('click', () => approveReview(btn.dataset.approve)));
    host.querySelectorAll('[data-reject]').forEach(btn => btn.addEventListener('click', () => openRejectModal(btn.dataset.reject, btn.dataset.user)));
    host.querySelectorAll('.history-thumb').forEach(t => t.addEventListener('click', () => openLightbox(t.dataset.url)));
  } catch (e) {
    host.innerHTML = `<div class="alert alert-danger">Could not load: ${e.message || e}</div>`;
  }
}

async function renderAdminRow(r, status) {
  let thumbUrl = '';
  try {
    // Admin needs full path including the owner's identity id; the screenshotKey we
    // stored is partial. To resolve back, we need the owner-prefixed path. The
    // simplest correct approach: have admins look up via the per-row stored prefix.
    // Since the data model doesn't currently store the owner identityId, we approximate
    // by trying both: the current admin's path is wrong; instead we rely on the
    // Storage 'guest' or list query. For now we store the full path on create —
    // see TODO note. For this build the upload also writes a copy of the path:
    if (r.screenshotPath) {
      thumbUrl = (await getUrl({ path: r.screenshotPath, options:{ expiresIn:3600 } })).url.toString();
    }
  } catch {}
  const dateStr = r.submittedAt ? new Date(r.submittedAt).toLocaleDateString('en-GB', { day:'2-digit', month:'short', year:'2-digit' }) : '';
  const actions = status === 'pending'
    ? `<div style="display:flex;gap:6px;flex-shrink:0;">
        <button class="btn btn-success btn-sm" data-approve="${r.id}">Approve</button>
        <button class="btn btn-danger btn-sm" data-reject="${r.id}" data-user="${escapeAttr(r.userName)}">Reject</button>
      </div>`
    : `<span class="badge badge-${status}">${status}</span>`;
  return `<div class="history-row">
    <div class="history-thumb" data-url="${thumbUrl}" style="background-image:url('${thumbUrl}');"></div>
    <div style="flex:1;min-width:0;">
      <div style="font-size:13px;font-weight:600;">${escapeHtml(r.userName || '')}</div>
      <div style="font-size:11px;color:var(--text3);">${dateStr} · ${r.platform || 'Google'} · ${r.monthKey}</div>
      ${r.adminComment ? `<div style="font-size:12px;color:var(--red);margin-top:4px;padding:5px 9px;background:var(--red-light);border-radius:4px;">${escapeHtml(r.adminComment)}</div>` : ''}
    </div>
    ${actions}
  </div>`;
}

async function approveReview(id) {
  try {
    const res = await client.models.Review.update({
      id,
      status: 'approved',
      decidedAt: new Date().toISOString(),
      decidedBy: currentEmail,
    });
    if (res.errors?.length) throw new Error(res.errors[0].message);
    toast('Approved.', 'success');
    loadAdminList('pending');
  } catch (e) {
    toast('Approve failed: ' + (e.message || e), 'danger');
  }
}

let rejectingId = null;
function openRejectModal(id, user) {
  rejectingId = id;
  document.getElementById('reject-name').textContent = user || 'the user';
  document.getElementById('reject-text').value = '';
  document.getElementById('reject-modal').classList.remove('hidden');
}
document.getElementById('reject-cancel').addEventListener('click', () => document.getElementById('reject-modal').classList.add('hidden'));
document.getElementById('reject-confirm').addEventListener('click', async () => {
  const text = document.getElementById('reject-text').value.trim();
  if (!text) { document.getElementById('reject-text').style.borderColor = 'var(--red)'; return; }
  document.getElementById('reject-modal').classList.add('hidden');
  try {
    const res = await client.models.Review.update({
      id: rejectingId,
      status: 'rejected',
      adminComment: text,
      decidedAt: new Date().toISOString(),
      decidedBy: currentEmail,
    });
    if (res.errors?.length) throw new Error(res.errors[0].message);
    toast('Rejected.', 'success');
    loadAdminList('pending');
  } catch (e) {
    toast('Reject failed: ' + (e.message || e), 'danger');
  }
});

// Invite new user
document.getElementById('inv-btn').addEventListener('click', async () => {
  const name = document.getElementById('inv-name').value.trim();
  const email = document.getElementById('inv-email').value.trim().toLowerCase();
  const role = document.getElementById('inv-role').value;
  const errEl = document.getElementById('inv-error');
  errEl.classList.add('hidden');
  if (!name || !email) { errEl.textContent = 'Name and email are required.'; errEl.classList.remove('hidden'); return; }
  if (!/^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$/.test(email)) {
    errEl.textContent = 'Enter a valid email.'; errEl.classList.remove('hidden'); return;
  }
  const btn = document.getElementById('inv-btn');
  btn.disabled = true; btn.innerHTML = '<span class="spinner"></span>Sending…';
  try {
    const res = await client.mutations.inviteUser({ email, fullName: name, role });
    if (res.errors?.length) throw new Error(res.errors[0].message);
    const out = res.data || {};
    if (out.ok) {
      toast(`Invite sent. ${email} will get a welcome email from Cognito with a temporary password.`, 'success');
      document.getElementById('inv-name').value = '';
      document.getElementById('inv-email').value = '';
    } else {
      errEl.textContent = out.error || 'Unknown error.';
      errEl.classList.remove('hidden');
    }
  } catch (e) {
    errEl.textContent = humanAuthError(e);
    errEl.classList.remove('hidden');
  } finally {
    btn.disabled = false; btn.innerHTML = 'Send invite';
  }
});

// ----------------------------- HELPERS -------------------------------------
function escapeHtml(s) { return String(s || '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
function escapeAttr(s) { return escapeHtml(s).replace(/"/g, '&quot;'); }

function toast(msg, kind = 'info') {
  const t = document.createElement('div');
  t.className = 'alert alert-' + kind;
  t.style.cssText = 'max-width:320px;box-shadow:0 4px 20px rgba(0,0,0,.15);animation:slideIn .2s ease;';
  t.textContent = msg;
  document.getElementById('toast-host').appendChild(t);
  setTimeout(() => t.remove(), 3500);
}

function humanAuthError(e) {
  const m = e?.message || e?.name || String(e);
  if (/NotAuthorizedException/.test(m) || /Incorrect username or password/.test(m)) return 'Wrong email or password.';
  if (/UserNotFoundException/.test(m)) return 'No account with that email.';
  if (/CodeMismatchException/.test(m)) return 'That code is incorrect or expired.';
  if (/LimitExceededException/.test(m)) return 'Too many attempts; try again in a few minutes.';
  if (/InvalidPasswordException/.test(m)) return 'Password too weak: needs 8+ chars including upper, lower, and number.';
  return m;
}

// Lightbox
document.getElementById('lightbox').addEventListener('click', () => document.getElementById('lightbox').classList.add('hidden'));
function openLightbox(url) {
  if (!url) return;
  document.getElementById('lightbox-img').src = url;
  document.getElementById('lightbox').classList.remove('hidden');
}

// ----------------------------- WITHDRAW REVIEW -----------------------------
async function withdrawReview(id) {
  if (!confirm('Withdraw this pending review? This cannot be undone.')) return;
  try {
    const review = staffReviews.find(r => r.id === id);
    if (review?.screenshotPath) {
      try { await removeFromStorage({ path: review.screenshotPath }); } catch (_) { /* ignore */ }
    }
    const res = await client.models.Review.delete({ id });
    if (res.errors?.length) throw new Error(res.errors[0].message);
    toast('Review withdrawn.', 'success');
    refreshStaff();
  } catch (e) {
    toast('Could not withdraw: ' + (e.message || e), 'danger');
  }
}

// ----------------------------- ANNOUNCEMENT --------------------------------
async function loadAnnouncement() {
  const banner = document.getElementById('staff-announcement');
  const textEl = document.getElementById('staff-announcement-text');
  if (!banner || !textEl) return;
  try {
    const res = await client.models.Announcement.list({
      filter: { active: { eq: true } },
      limit: 1
    });
    if (res.errors?.length) { banner.classList.add('hidden'); return; }
    const list = res.data || [];
    if (list.length > 0 && list[0].text) {
      textEl.textContent = list[0].text;
      banner.classList.remove('hidden');
    } else {
      banner.classList.add('hidden');
    }
  } catch (_) {
    banner.classList.add('hidden');
  }
}

async function loadAdminAnnouncement() {
  const input = document.getElementById('announcement-input');
  if (!input) return;
  try {
    const res = await client.models.Announcement.list({
      filter: { active: { eq: true } },
      limit: 1
    });
    if (res.errors?.length) return;
    const list = res.data || [];
    input.value = list[0]?.text || '';
  } catch (_) { /* ignore */ }
}

async function saveAnnouncementClick() {
  const input = document.getElementById('announcement-input');
  const savedMsg = document.getElementById('ann-saved-msg');
  const text = (input?.value || '').trim();
  if (!text) { toast('Enter a message first, or click Clear to remove.', 'warning'); return; }
  const btn = document.getElementById('ann-save-btn');
  btn.disabled = true; btn.innerHTML = '<span class="spinner"></span>Saving…';
  try {
    const existing = await client.models.Announcement.list({ filter: { active: { eq: true } } });
    for (const a of (existing.data || [])) {
      await client.models.Announcement.update({ id: a.id, active: false });
    }
    const res = await client.models.Announcement.create({ text, active: true });
    if (res.errors?.length) throw new Error(res.errors[0].message);
    if (savedMsg) {
      savedMsg.textContent = 'Announcement posted to all staff ✓';
      savedMsg.classList.remove('hidden');
      setTimeout(() => savedMsg.classList.add('hidden'), 3000);
    }
    toast('Announcement posted.', 'success');
  } catch (e) {
    toast('Could not save: ' + (e.message || e), 'danger');
  } finally {
    btn.disabled = false; btn.innerHTML = 'Post announcement';
  }
}

async function clearAnnouncementClick() {
  const btn = document.getElementById('ann-clear-btn');
  btn.disabled = true; btn.innerHTML = '<span class="spinner"></span>Clearing…';
  try {
    const existing = await client.models.Announcement.list({ filter: { active: { eq: true } } });
    for (const a of (existing.data || [])) {
      await client.models.Announcement.update({ id: a.id, active: false });
    }
    const input = document.getElementById('announcement-input');
    if (input) input.value = '';
    toast('Announcement cleared.', 'success');
  } catch (e) {
    toast('Could not clear: ' + (e.message || e), 'danger');
  } finally {
    btn.disabled = false; btn.innerHTML = 'Clear';
  }
}

const annSaveBtn = document.getElementById('ann-save-btn');
const annClearBtn = document.getElementById('ann-clear-btn');
if (annSaveBtn) annSaveBtn.addEventListener('click', saveAnnouncementClick);
if (annClearBtn) annClearBtn.addEventListener('click', clearAnnouncementClick);
